apiVersion: batch/v1
kind: Job
metadata:
  name: efcore-migrate
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: migrate
          image: 949527796968.dkr.ecr.eu-west-1.amazonaws.com/books-backend:latest
          command: ["dotnet", "BooksEcommerce.Api.dll", "database", "update"]
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=mssql-service,1433;Database=BooksEcommerceDb;User Id=sa;Password=Cover@2025;Encrypt=False;"
            - name: AllowedOrigins
              value: "http://frontend-url-1,http://frontend-url-2"
      restartPolicy: Never