apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-frontend
  template:
    metadata:
      labels:
        app: books-frontend
    spec:
      containers:
        - name: books-frontend
          image: 949527796968.dkr.ecr.eu-west-1.amazonaws.com/books-frontend:latest
          ports:
            - containerPort: 80